site_name: SRXDModdingDocs
repo_url: https://github.com/SRXDModdingGroup/SRXDModdingDocs
repo_name: SRXDModdingGroup/SRXDModdingDocs

theme:
    language: en

    name: material

    logo: https://github.com/SRXDModdingGroup.png?size=40

    features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.instant

    palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - mdx_truly_sane_lists


